kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true

  metricsConfig:
    # -- Create the configmap.
    create: true

  config:
      excludeKyvernoNamespace: true
      resourceFiltersExcludeNamespaces:
        - kube-system
        - kube-node-lease
        - kube-public
        - kyverno
        - prometheus
        - argocd