kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true
  metricsConfig:
    # -- Create the configmap.
    create: true
  
  # Configure Kyverno's global resource filters
  # This will exclude matching resources from all Kyverno processing.
  config:
    resourceFilters:
      # Exclude prometheus-node-exporter Pods.
      # Format: "[kind,namespace,name,selector]" (use * for wildcard)
      # Adjust namespace and labels to match your node-exporter deployment.
      - "[Pod,prometheus,*,app.kubernetes.io/name=node-exporter]"
      # You might also want to exclude other system components or specific namespaces globally:
      # - "[*,kube-system,*,*]" # Exclude all resources in kube-system (use with caution)
      # - "[Event,*,*,*]" # Commonly excluded
        