kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true
  metricsConfig:
    # -- Create the configmap.
    create: true
  admissionController:
    policyExceptions:
      # -- Enable PolicyException processing.
      # This is the recommended way to enable the feature via the Helm chart.
      enable: true
      # namespace: "kyverno" # Optional: Define if you want to scope where Kyverno looks for PolicyException CRs. Empty (default) means all namespaces.
  
  # Configure Kyverno's global resource filters
  # This will exclude matching resources from all Kyverno processing.
  config:
    # enablePolicyExceptions: true # This might be redundant or overridden if admissionController.policyExceptions.enable is used.
    excludeKyvernoNamespace: true
    resourceFilters:
      # Exclude prometheus-node-exporter resources from all Kyverno processing.
      # This is a global exclusion. If you need to exclude these resources from specific
      # policies only, that configuration should be done within the policy definitions.
      # Format: "[kind,namespace,name,selector]" (use * for wildcard)
      # Adjust namespace and labels to match your node-exporter deployment.
      # The following assumes prometheus-node-exporter DaemonSets and Pods are in the 'prometheus'
      # namespace and have the label 'app.kubernetes.io/name: prometheus-node-exporter'.
      # Use '*' for the resource name if the selector is specific enough.
      - "[Pod,opensearch,*,app.kubernetes.io/name: opentelemetry-collector]"
      - "[DaemonSet,prometheus,*,app.kubernetes.io/name: prometheus-node-exporter]"
      - "[Pod,prometheus,*,app.kubernetes.io/name: prometheus-node-exporter]" # Old filter based on label
      # Filters below are based on common names/labels for prometheus-node-exporter
      # Verify the actual namespace, name, and labels in your cluster
      #- "[DaemonSet,prometheus,*,app.kubernetes.io/name: node-exporter]" # Filter by label
      #- "[Pod,prometheus,*,app.kubernetes.io/name: node-exporter]" # Filter by label
      # You might also want to exclude other system components or specific namespaces globally:
      - "[*,kube-system,*,*]" # Exclude all resources in kube-system (use with caution)
      - "[*,kube-node-lease,*,*]"
      - "[*,kube-public,*,*]"
      - "[Event,*,*,*]" # Commonly excluded

kyverno-policies:
  podSecurityStandard: baseline
  validationFailureActionOverrides:
    all:
      - action: audit
        namespaces:
          - kube-system
          - kube-node-lease
          - kube-public
          - kyverno