kyverno-policies:
  config: 
    excludeKyvernoNamespace: true
    webhooks:
        # Exclude namespaces
        namespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kube-node-lease
                - kube-public
                - prometheus
                - argocd
                
kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true
  metricsConfig:
    # -- Create the configmap.
    create: true
  
  # Configure Kyverno's global resource filters
  # This will exclude matching resources from all Kyverno processing.
  config:
    resourceFilters:
      # Exclude prometheus-node-exporter resources from all Kyverno processing.
      # This is a global exclusion. If you need to exclude these resources from specific
      # policies only, that configuration should be done within the policy definitions.
      # Format: "[kind,namespace,name,selector]" (use * for wildcard)
      # Adjust namespace and labels to match your node-exporter deployment.
      # The following assumes prometheus-node-exporter DaemonSets and Pods are in the 'prometheus'
      # namespace and have the label 'app.kubernetes.io/name: prometheus-node-exporter'.
      # Use '*' for the resource name if the selector is specific enough.
      - "[DaemonSet,prometheus,prometheus-prometheus-node-exporter]"
      - "[Pod,prometheus,prometheus-prometheus-node-exporter*]"
      - "[*,argocd,*,*]"
      # You might also want to exclude other system components or specific namespaces globally:
      - "[*,kube-system,*,*]" # Exclude all resources in kube-system (use with caution)
      - "[*,kube-node-lease,*,*]"
      - "[*,kube-public,*,*]"
      # - "[Event,*,*,*]" # Commonly excluded