kyverno:
  config: 
    excludeKyvernoNamespace: true
    webhooks:
        # Exclude namespaces
        namespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
                - kube-system
                - kube-node-lease
                - kube-public
                - prometheus
                - argocd
              
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true

  metricsConfig:
    # -- Create the configmap.
    create: true
        