kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true

kyverno-policies:
  podSecurityStandard: baseline
  podSecuritySeverity: medium

policy-reporter:
  enabled: true
  metrics:
    enabled: true
  