kyverno:
  grafana:
    # -- Enable grafana dashboard creation.
    enabled: true

  metricsConfig:
    # -- Create the configmap.
    create: true

  config:
    resourceFiltersExcludeNamespaces:
      # -- Exclude namespaces from the resource filters.
      - kube-system
      - kyverno
      - argocd
      - prometheus